### ISSUE TITLE
Blockscout Version

### ISSUE THREAD

**Issue by Rambatino** [skylenet/ethereum-helm-charts#90]
Hello, is there any plan to bump the skylenet/blockscout image to use a more recent blockscout version here: https://github.com/blockscout/blockscout/releases?

**Comment by Rambatino** [comment]
Hi @skylenet. So it came up with this new version, however I'm not sure why it can't connect to the database (all config the same as before)

```
19:49:32.182 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'
The database for Explorer.Repo has already been created
19:49:32.594 [warning] Description: 'Authenticity is not established by certificate path validation'                                                                                                                                                                                                                          Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              19:49:32.597 [warning] Description: 'Authenticity is not established by certificate path validation'                                                                                                                                                                                                                          Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              19:49:32.725 [info]  Migrations already up                                                                                                                                                                                                                                                                               2022-07-28T19:49:39.325 application=tzdata [info] tzdata release in place is from a file last modified Fri, 22 Oct 2021 02:20:47 GMT. Release file on server was last modified Wed, 16 Mar 2022 13:36:02 GMT.                                                                                                            2022-07-28T19:49:41.931 application=tzdata [info] Tzdata has updated the release from 2021e to 2022a                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              2022-07-28T19:49:49.027 [warning] Description: 'Authenticity is not established by certificate path validation'                                                                                                                                                                                                               Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'
2022-07-28T19:49:49.027 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

2022-07-28T19:49:49.027 [warning] Description: 'Authenticity is not established by certificate path validation'
     Reason: 'Option {verify, verify_peer} and cacertfile/cacerts is missing'

... many of these warnings

2022-07-28T19:49:49.118 application=explorer [warning] Failed to get exchange rates with reason 'Source URL is nil'.
2022-07-28T19:49:49.219 [notice] Application explorer exited: Explorer.Application.start(:normal, []) returned an error: shutdown: failed to start child: Explorer.Chain.Events.Listener
    ** (EXIT) an exception was raised:
        ** (MatchError) no match of right hand side value: {:error, %Postgrex.Error{connection_id: nil, message: nil, postgres: %{code: :protocol_violation, message: "pgbouncer cannot connect to server", pg_code: "08P01", severity: "FATAL"}, query: nil}}
            (explorer 0.0.1) lib/explorer/chain/events/listener.ex:15: Explorer.Chain.Events.Listener.init/1
            (stdlib 3.17) gen_server.erl:423: :gen_server.init_it/2
            (stdlib 3.17) gen_server.erl:390: :gen_server.init_it/6
            (stdlib 3.17) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
2022-07-28T19:49:49.220 [notice] Application cbor exited: :stopped
2022-07-28T19:49:49.228 [notice] Application con_cache exited: :stopped
2022-07-28T19:49:49.229 [notice] Application spandex_ecto exited: :stopped
2022-07-28T19:49:49.237 [notice] Application que exited: :stopped
2022-07-28T19:49:49.237 [notice] Application ex_utils exited: :stopped
2022-07-28T19:49:49.237 [notice] Application memento exited: :stopped
2022-07-28T19:49:49.244 [notice] Application mnesia exited: :stopped
2022-07-28T19:49:49.244 [notice] Application prometheus_ecto exited: :stopped
2022-07-28T19:49:49.244 [notice] Application prometheus_ex exited: :stopped
2022-07-28T19:49:49.247 [notice] Application prometheus exited: :stopped
2022-07-28T19:49:49.247 [notice] Application quantile_estimator exited: :stopped
2022-07-28T19:49:49.248 [notice] Application postgrex exited: :stopped
2022-07-28T19:49:49.248 [notice] Application nimble_csv exited: :stopped
2022-07-28T19:49:49.248 [notice] Application poison exited: :stopped
2022-07-28T19:49:49.248 [notice] Application phoenix_html exited: :stopped
2022-07-28T19:49:49.248 [notice] Application math exited: :stopped
2022-07-28T19:49:49.249 [notice] Application ecto_sql exited: :stopped
2022-07-28T19:49:49.250 [notice] Application db_connection exited: :stopped
2022-07-28T19:49:49.250 [notice] Application connection exited: :stopped
** (Mix) Could not start application explorer: Explorer.Application.start(:normal, []) returned an error: shutdown: failed to start child: Explorer.Chain.Events.Listener
    ** (EXIT) an exception was raised:
        ** (MatchError) no match of right hand side value: {:error, %Postgrex.Error{connection_id: nil, message: nil, postgres: %{code: :protocol_violation, message: "pgbouncer cannot connect to server", pg_code: "08P01", severity: "FATAL"}, query: nil}}
            (explorer 0.0.1) lib/explorer/chain/events/listener.ex:15: Explorer.Chain.Events.Listener.init/1
            (stdlib 3.17) gen_server.erl:423: :gen_server.init_it/2
            (stdlib 3.17) gen_server.erl:390: :gen_server.init_it/6
            (stdlib 3.17) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
2022-07-28T19:49:49.251 [notice] Application ecto exited: :stopped
2022-07-28T19:49:49.251 [notice] Application dataloader exited: :stopped
2022-07-28T19:49:49.251 [notice] Application comeonin exited: :stopped
2022-07-28T19:49:49.252 [notice] Application briefly exited: :stopped
2022-07-28T19:49:49.252 [notice] Application bcrypt_elixir exited: :stopped
2022-07-28T19:49:49.252 [notice] Application tesla exited: :stopped
2022-07-28T19:49:49.252 [notice] Application runtime_tools exited: :stopped
```

Will keep looking into it, I don't necessarily know if the warnings are important regarding pgbouncer. 

I'm going to try and drop the database and rebuild from the archive node and will let you know!

**Comment by Rambatino** [comment]
Okay managed to get it working by passing it an admin database url then it errored because it needed a database called "pool" which was super weird because the database_url is:

```
postgres://tsdbadmin:AVREDACTEDcA@db-sandbox.a.timescaledb.io:14494/pool-blockscout?sslmode=require
```

Well it's the connection pool to the database, but I think it seems to want to connect to the database called "postgres" it then instantiates that.

All very confusing, but it seems to be the internals of blockscout rather than helm chart that uses it! 

So all is good!

Thank you very much for your help :)
